### ISSUE TITLE
Organize Meijo visit #1

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#62]
- Eight students and two professors from Meijo University will fly in on Feb 23 and leave March 1.
- They arrive at hotel in Davis on the evening of Feb 23. Jason will likely join them for dinner that evening.
- They are staying at the University Park Inn and Suites.
- Leaving Davis for SF on the 27th in evening. Possible dinner that night too.
- They will come to our critical design reviews that are scheduled on the 27th.
- They will participate in Engineering Week activities the 24th.

# Tasks
- [x] Create schedule for the group.
- [x] Organize the lunch: select students, order catering, find space, selected students will need to share something about their culture.
- [x] Organize the campus tour (Monday)
- [ ] Get campus parking passes
- [x] Schedule in e week events on friday
- [x] Get Rube Goldberg materials for the e-week activity
- [x] Schedule in the Sacramento Japanese exhibit on Sat or Sun
- [x] Think about other Sac area options for the weekend day
- [x] Check in with Petros about a possible snow visit for the weekend.
- [x] Schedule and EFL tour on Monday.
- [x] TAs (optional), Jason, and them have lunch at MU on Friday
- [ ] Catered lunch on Monday
- [x] Friday night dinner at Davis restaurant
- [x] Jason will host dinner the weekend day they come to Sacramento
- [ ] Announce and lottery to choose students for lunch in class (or online) (can be done in 22/23 sections)
- [x] Make a statement explaining culture game

**Comment by ixjlyons** [comment]
Clarification needed: is Feb 27 their last day in Davis and the rest of the trip (through March 1) will be in SF?

**Comment by moorepants** [comment]
I think they are planning to leave Davis late afternoon or evening on the 27th. The remaining part of the trip will be in SF.

FYI, I emailed Kelley Weiss inquiring about the E Week events. Waiting on response.

**Comment by moorepants** [comment]
This could potentially be interesting for them on the weekend:

http://www.sacmag.com/Sacramento-Magazine/Arts-Culture/Sacramento-Events-Calendar/index.php/name/Kokoro-The-Story-of-Sacramentos-Lost-Japantown/event/12820/

**Comment by ixjlyons** [comment]
Request put in for Kemper 1131 for the catered lunch on Monday. It holds about 40 people.

**Comment by ixjlyons** [comment]
EFL tour is loosely scheduled for 10 or 11 on Monday the 27th. 9am is a bit early for the shop staff to set up glasses and whatnot, but it's flexible enough to schedule it so the students can attend a design review on Monday morning.

**Comment by ixjlyons** [comment]
I think this went pretty smoothly. Notes have been added to the instructor guide for most of my tasks.
